FROM node:18

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy app source
COPY . .

# Build React app
RUN npm run build

# Expose port
EXPOSE 3000

# Start command
CMD ["npm", "start"]
